apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aspireos

resources:
  - namespace.yaml
  - configmap.yaml
  - postgres.yaml
  - redis.yaml
  - backend.yaml
  - frontend.yaml
  - ingress.yaml

images:
  - name: registry.utho.io/asperiondigital/aspireos-backend
    newTag: latest
  - name: registry.utho.io/asperiondigital/aspireos-frontend
    newTag: latest

patches:
  - target:
      kind: Deployment
      name: "backend|frontend"
    patch: |-
      - op: add
        path: /spec/template/spec/imagePullSecrets
        value:
          - name: utho-registry
