apiVersion: v1
kind: Secret
metadata:
  name: aspireos-secrets
  namespace: aspireos
type: Opaque
stringData:
  SECRET_KEY: "y0DOv5L2amMjTiJYC3ODqjkCpceKL5hMjtecXj0X1Ml2fZTD5Lyj34AmrAJhpZGjHAcv_Lft_JNxJRJT4jCJpA"
  POSTGRES_PASSWORD: "Dasari@2004"
  DATABASE_URL: "postgresql+psycopg://aspireos:Dasari@2004@postgres:5432/aspireos"
